# Generated by Django 5.1.7 on 2025-03-23 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('ex_price', models.CharField(max_length=200)),
                ('price', models.CharField(max_length=200)),
                ('score', models.FloatField(default=0)),
                ('details', models.TextField()),
                ('description', models.TextField()),
                ('specification', models.TextField()),
                ('is_featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
