# Generated by Django 5.1.7 on 2025-03-23 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_products_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='ex_price',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
