# Generated by Django 5.1.7 on 2025-03-30 19:10

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_products_ex_price_alter_products_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='ex_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='price',
            field=models.DecimalField(decimal_places=2, default=22.0, max_digits=10),
            preserve_default=False,
        ),
    ]
