# Generated by Django 5.1.7 on 2025-03-30 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_products_ex_price_alter_products_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='ex_price',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='price',
            field=models.CharField(max_length=200),
        ),
    ]
