# Generated by Django 5.1.7 on 2025-04-01 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_subscriber_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
