# Generated by Django 5.1.7 on 2025-04-03 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_homeslider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=5.0, max_digits=3),
        ),
    ]
