# Generated by Django 5.1.7 on 2025-04-12 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_products_brand_remove_products_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='category',
            new_name='categories',
        ),
    ]
