# Generated by Django 5.1.7 on 2025-04-12 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_rename_category_products_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='categories',
        ),
        migrations.AddField(
            model_name='products',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='core.category'),
        ),
        migrations.AlterField(
            model_name='products',
            name='brand',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
